#!/usr/bin/env php
<?php

namespace BFF;

use BFF\Cli\Exception;

include __DIR__ . '/vendor/autoload.php';

date_default_timezone_set('UTC');

try {
    Cli\Task::init($argv);
} catch (Exception $e) {
    echo 'Error: ' . $e->getMessage() . PHP_EOL;
}